feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: basic

logging:
    level:
        web: DEBUG

spring:
    cloud:
        compatibility-verifier:
            enabled: false
    h2:
        console:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include: *

java:
    util:
        PropertyResourceBundle:
            encoding: ISO-8859-1

viacep:
    name: viacep
    url: https://viacep.com.br/ws
